services:

  extension:
    build: ./apps/extension

  backend:
    build:
      context: ./apps/backend
    container_name: prs_backend
    ports:
      - "8000:8000"
    volumes:
      - ./apps/backend:/app
    depends_on:
      - postgres
      - redis

  worker:
    build: ./apps/worker

  frontend:
    build:
      context: ./apps/frontend
    container_name: prs_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: postgres:16
    container_name: prs_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"

volumes:
  postgres_data: