export interface LanguagePatterns {
  keywords: string[];
  sections: string[];
  urlPatterns: RegExp[];
}

export const LANGUAGES: Record<string, LanguagePatterns> = {
  en: {
    keywords: [
      'privacy',
      'policy',
      'confidentiality',
      'confidential',
      'personal data',
      'data protection',
      'gdpr',
      'ccpa',
      'terms of service',
      'terms & conditions',
      'legal',
      'privacy statement',
      'cookie policy',
      'data collection',
      'data processing',
      'privacy notice',
      'privacy practices',
      'information practices',
      'data practices',
      'your privacy',
      'our privacy',
      'personal information',
      'personally identifiable',
      'sensitive information',
      'health information',
      'financial information',
      'location data',
      'device information',
      'usage data',
      'analytics',
      'tracking',
      'third party',
      'service providers',
      'data retention',
      'data deletion',
      'data access',
      'data portability',
      'right to know',
      'right to delete',
      'right to opt out',
      'consent',
      'opt-in',
      'opt-out',
      'cookies',
      'web beacons',
      'pixels',
      'security measures',
      'data security',
      'encryption',
      'compliance',
      'regulatory',
      'legal basis',
      'processing',
      'processor',
      'controller',
      'eu-us',
      'california consumer privacy',
      'ccpa',
      'gdpr',
      'caloppa',
      'personal data breach',
      'data breach',
      'notification',
      'children privacy',
      'coppa',
      'virginia',
      'colorado',
      'connecticut',
      'utah',
      'information security',
      'secure',
      'secured',
      'protect your data',
      'protecting your',
    ],
    sections: [
      'data collection',
      'information we collect',
      'what information',
      'how we collect',
      'how we use',
      'data sharing',
      'third parties',
      'data retention',
      'how long',
      'data protection',
      'your rights',
      'user rights',
      'consumer rights',
      'cookie',
      'cookies',
      'tracking',
      'gdpr',
      'ccpa',
      'security',
      'secure',
      'contact us',
      'privacy officer',
      'data controller',
      'data processor',
      'legal basis',
      'processing',
      'consent',
      'opt-out',
      'unsubscribe',
      'access your data',
      'correct your data',
      'delete your data',
      'data breach',
      'notification',
      'children',
      'coppa',
      'california',
      'virginia',
      'colorado',
      'connecticut',
      'utah',
      'retention policy',
      'privacy policy',
      'information practices',
      'our practices',
    ],
    urlPatterns: [
      /\/(privacy|legal|terms|confidentiality|cookie|data-protection|gdpr|policy|notice|practices|info|help)(?:\/|\.html|$|\?)/i,
    ],
  },

  fr: {
    keywords: [
      'confidentialité',
      'politique de confidentialité',
      'protection des données',
      'protection donnees',
      'protection-donnees',
      'politique de protection',
      'gestion des données',
      'données personnelles',
      'donnees personnelles',
      'rgpd',
      'conditions générales',
      'conditions d\'utilisation',
      'mentions légales',
      'politique de cookies',
      'collecte de données',
      'traitement des données',
      'donnees',
      'confidentialite',
      'infos client',
      'vos données',
      'votre confidentialité',
      'votre confidentialite',
      'utilisation des données',
      'utilisation donnees',
      'partageons vos',
      'partage des données',
      'partage donnees',
      'tiers',
      'consentement',
      'droits',
      'accès aux informations',
      'contrôle des données',
      'controle donnees',
      'informations personnelles',
      'informations client',
      'données clients',
      'donnees clients',
      'politique de',
      'notice de confidentialité',
      'notice confidentialite',
      'vie privée',
      'vie privee',
      'durée de conservation',
      'duree de conservation',
      'sécurité des données',
      'securite donnees',
      'respect de la vie privée',
      'respect vie privee',
      'droit d\'accès',
      'droit a l\'oubli',
      'droit de rectification',
      'droit de portabilité',
      'portabilite donnees',
      'limitation du traitement',
      'opposition',
      'opt-out',
      'désinscription',
      'desabonnement',
      'responsable de traitement',
      'responsable traitement',
      'responsable des données',
      'sous-traitant',
      'base légale',
      'base legale',
      'finalité',
      'finalite',
      'consentement explicite',
      'cookies',
      'pixels',
      'analytics',
      'suivi',
      'publicités',
      'publicites',
      'ciblage',
      'partenaires',
      'informations de contact',
      'contact',
      'sécurité',
      'securite',
      'données sensibles',
      'donnees sensibles',
      'données de santé',
      'donnees sante',
      'données financières',
      'donnees financieres',
      'localisation',
      'géolocalisation',
      'geolocalisation',
      'notification de violation',
      'notification violation',
      'enfants',
      'droits des enfants',
      'conservation des données',
    ],
    sections: [
      'données personnelles',
      'donnees personnelles',
      'collecte de données',
      'collecte donnees',
      'que collectons',
      'quelles données',
      'utilisation des données',
      'utilisation donnees',
      'comment utilisons',
      'partage des données',
      'partage donnees',
      'avec qui partageons',
      'droit d\'accès',
      'droit a l\'oubli',
      'droit de modification',
      'droit de rectification',
      'droits des utilisateurs',
      'vos droits',
      'consentement',
      'cookies',
      'pixel',
      'analytics',
      'responsable de traitement',
      'responsable traitement',
      'sous-traitant',
      'base légale',
      'base legale',
      'durée de conservation',
      'duree de conservation',
      'sécurité',
      'securite',
      'mesures de sécurité',
      'mesures securite',
      'nous contacter',
      'nous contactez',
      'infos client',
      'informations personnelles',
      'donnees personnelles',
      'politique de confidentialité',
      'vie privée',
      'vie privee',
      'protection des données',
      'protection donnees',
      'contact',
      'question',
      'désinscription',
      'desabonnement',
      'opt-out',
      'opposition',
      'plainte',
      'recours',
      'droit de portabilité',
      'portabilite',
      'limitation du traitement',
      'conservation',
      'notification',
    ],
    urlPatterns: [
      /\/(politique|protection|donnees|confidentialite|confidentialité|mentions|cookies|rgpd|protection-donnees|help|customer|infos|politique-confidentialite|avis|notice|support)(?:\/|\.html|$|\?)/i,
    ],
  },

  es: {
    keywords: [
      'privacidad',
      'política de privacidad',
      'protección de datos',
      'datos personales',
      'rgpd',
      'lopd',
      'lssi',
      'términos de servicio',
      'condiciones de uso',
      'aviso legal',
      'política de cookies',
      'recopilación de datos',
      'tratamiento de datos',
      'información personal',
      'información privada',
      'privacidad del usuario',
      'su privacidad',
      'datos del cliente',
      'información del cliente',
      'protección de la privacidad',
      'política de protección',
      'gestión de datos',
      'consentimiento',
      'derechos del usuario',
      'derechos de privacidad',
      'información de contacto',
      'derecho de acceso',
      'derecho al olvido',
      'derecho de rectificación',
      'derecho de portabilidad',
      'derecho de oposición',
      'limitación del tratamiento',
      'cesión de datos',
      'terceros',
      'proveedores de servicios',
      'duración de conservación',
      'seguridad de datos',
      'seguridad de la información',
      'cookies',
      'seguimiento',
      'análisis',
      'publicidad dirigida',
      'publicidad personalizada',
      'partners',
      'responsable del tratamiento',
      'encargado del tratamiento',
      'base legal',
      'finalidad del tratamiento',
      'escaneo',
      'desuscripción',
      'opt-out',
      'notificación de incidente',
      'incidente de datos',
      'menores de edad',
      'información de salud',
      'información financiera',
      'ubicación',
      'localización',
      'dispositivo',
      'información de dispositivo',
      'análisis de datos',
      'información de uso',
    ],
    sections: [
      'datos personales',
      'recopilación de datos',
      'qué datos recopilamos',
      'información que recopilamos',
      'cómo utilizamos',
      'uso de los datos',
      'cómo usamos',
      'compartir datos',
      'cesión de datos',
      'derechos del usuario',
      'sus derechos',
      'cookies',
      'tecnologías de seguimiento',
      'seguimiento',
      'seguridad',
      'medidas de seguridad',
      'responsable del tratamiento',
      'encargado del tratamiento',
      'base legal',
      'duración de conservación',
      'período de retención',
      'contacto',
      'póngase en contacto',
      'derechos de acceso',
      'derechos de rectificación',
      'derechos de supresión',
      'derechos de portabilidad',
      'derechos de oposición',
      'quejas',
      'reclamaciones',
      'política de privacidad',
      'aviso de privacidad',
      'privacidad',
      'información personal',
      'información privada',
      'información sensible',
      'derecho al olvido',
      'conservación de datos',
    ],
    urlPatterns: [
      /\/(privacidad|proteccion|datos|aviso|legal|cookies|terminos|condiciones|rgpd|politica|ayuda|support)(?:\/|\.html|$|\?)/i,
    ],
  },

  de: {
    keywords: [
      'datenschutz',
      'datenschutzerklärung',
      'datenschutzrichtlinie',
      'impressum',
      'persönliche daten',
      'personliche daten',
      'personendaten',
      'datenverarbeitung',
      'dsgvo',
      'cookies',
      'nutzungsbedingungen',
      'allgemeine geschäftsbedingungen',
      'agb',
      'datenschutzbeauftragte',
      'datenschutzbeauftragter',
      'ihre daten',
      'ihre privatsphäre',
      'ihre privatsphaere',
      'datenverkehr',
      'datensicherheit',
      'datenschutz-grundverordnung',
      'daten personenbezogen',
      'verarbeitung personenbezogener',
      'informationen zum datenschutz',
      'informationen datenschutz',
      'schutz ihrer daten',
      'schutz ihrer informationen',
      'datenaustausch',
      'datenfreigabe',
      'datenweitergabe',
      'bestimmungen datenschutz',
      'richtlinien datenschutz',
      'zustimmung',
      'einwilligung',
      'widerspruchsrecht',
      'widerspruch',
      'opt-out',
      'abmeldung',
      'abbestellung',
      'recht auf auskunft',
      'recht auf einsicht',
      'recht auf löschung',
      'recht auf berichtigung',
      'recht auf datenportabilität',
      'recht auf datenübertragbarkeit',
      'datenminimierung',
      'datensparsamkeit',
      'speicherbegrenzung',
      'aufbewahrung von daten',
      'aufbewahrungsdauer',
      'datenschutzverletzung',
      'sicherheit',
      'verschlüsselung',
      'datenschutzmassnahmen',
      'datenschutzmaßnahmen',
      'dritte',
      'dienstleister',
      'datenverarbeiter',
      'auftragsverarbeiter',
      'verantwortliche stelle',
      'kontakt',
      'fragen',
      'fragen zum datenschutz',
      'gesundheitsdaten',
      'finanzdaten',
      'standort',
      'geolocation',
      'geräteinformationen',
      'nutzungsdaten',
      'benachrichtigung',
      'datenmitteilung',
    ],
    sections: [
      'persönliche daten',
      'personliche daten',
      'personendaten',
      'datenerfassung',
      'welche daten',
      'daten die wir erfassen',
      'verarbeitung von daten',
      'verwendung von daten',
      'wie verwenden wir',
      'datenweitergabe',
      'weitergabe an dritte',
      'datenaustausch',
      'rechte des benutzers',
      'ihre rechte',
      'benutzerrechte',
      'cookies',
      'tracking',
      'verfolgung',
      'sicherheit',
      'datensicherheit',
      'verschlüsselung',
      'recht auf auskunft',
      'recht auf löschung',
      'recht auf berichtigung',
      'recht auf datenportabilität',
      'recht auf widerspruch',
      'widerspruchsrecht',
      'einwilligung',
      'zustimmung',
      'rechtsgrundlage',
      'speicherbegrenzung',
      'aufbewahrungsdauer',
      'kontakt',
      'kontaktieren sie uns',
      'fragen',
      'datenschutzerklärung',
      'datenschutzrichtlinie',
      'impressum',
      'dsgvo',
      'datenschutz',
      'recht auf vergessenwerden',
      'speicherung',
    ],
    urlPatterns: [
      /\/(datenschutz|impressum|agb|nutzungsbedingungen|cookies|dsgvo|privacy|datenschutzerklarung|hilfe|support)(?:\/|\.html|$|\?)/i,
    ],
  },

  it: {
    keywords: [
      'privacy',
      'protezione dati',
      'dati personali',
      'gdpr',
      'rgpd',
      'condizioni d\'uso',
      'informativa sulla privacy',
      'informativa privacy',
      'politica sulla privacy',
      'politica privacy',
      'cookie',
      'trattamento dati',
      'trattamento dei dati',
      'informazioni personali',
      'informazioni private',
      'tue informazioni',
      'vostra privacy',
      'la vostra privacy',
      'dati dei clienti',
      'informazioni clienti',
      'protezione della privacy',
      'protezione della tua privacy',
      'gestione dati',
      'consentimento',
      'diritti dell\'utente',
      'diritti di privacy',
      'informazioni di contatto',
      'diritto di accesso',
      'diritto di cancellazione',
      'diritto di rettifica',
      'diritto di portabilità',
      'diritto di opposizione',
      'limitazione del trattamento',
      'condivisione dati',
      'cedenza dati',
      'terze parti',
      'fornitori di servizi',
      'durata della conservazione',
      'periodo di conservazione',
      'sicurezza dei dati',
      'sicurezza dell\'informazione',
      'monitoraggio',
      'tracciamento',
      'analisi',
      'pubblicità mirata',
      'partner',
      'titolare del trattamento',
      'responsabile del trattamento',
      'base giuridica',
      'finalità del trattamento',
      'iscrizione',
      'disiscrizione',
      'opt-out',
      'notifica di violazione',
      'violazione dei dati',
      'minori',
      'dati sanitari',
      'dati finanziari',
      'localizzazione',
      'geolocalizzazione',
      'informazioni dispositivo',
      'dati di utilizzo',
    ],
    sections: [
      'dati personali',
      'raccolta dati',
      'quali dati raccogliamo',
      'informazioni che raccogliamo',
      'come utilizziamo',
      'utilizzo dei dati',
      'come usiamo',
      'condivisione dati',
      'cedenza dati',
      'diritti dell\'utente',
      'tuoi diritti',
      'cookie',
      'tecnologie di tracciamento',
      'tracciamento',
      'sicurezza',
      'misure di sicurezza',
      'titolare del trattamento',
      'base giuridica',
      'durata della conservazione',
      'periodo di conservazione',
      'contatti',
      'contattaci',
      'diritto di accesso',
      'diritto di rettifica',
      'diritto di cancellazione',
      'diritto di portabilità',
      'diritto di opposizione',
      'reclami',
      'ricorsi',
      'politica sulla privacy',
      'informativa sulla privacy',
      'privacy',
      'informazioni personali',
      'informazioni private',
      'informazioni sensibili',
      'diritto all\'oblio',
      'conservazione dei dati',
    ],
    urlPatterns: [
      /\/(privacy|protezione|dati|condizioni|cookie|informativa|politica|protezione-dati|aiuto|support)(?:\/|\.html|$|\?)/i,
    ],
  },
};

export function getLanguagePatterns(url: string, content: string, title?: string): LanguagePatterns {
  const text = `${url} ${title || ''} ${content}`.toLowerCase();

  // Détecte la langue par les patterns d'URL et mots-clés
  for (const [lang, patterns] of Object.entries(LANGUAGES)) {
    // Vérifier les patterns d'URL
    if (patterns.urlPatterns.some((pattern) => pattern.test(url))) {
      return patterns;
    }

    // Vérifier les mots-clés dominants
    const matchedKeywords = patterns.keywords.filter((kw) =>
      text.includes(kw.toLowerCase())
    );

    if (matchedKeywords.length >= 5) {
      return patterns;
    }
  }

  // Par défaut, retourner l'anglais
  return LANGUAGES.en;
}

export function getAllKeywords(): string[] {
  return Object.values(LANGUAGES).flatMap((lang) => lang.keywords);
}

export function getAllSections(): string[] {
  return Object.values(LANGUAGES).flatMap((lang) => lang.sections);
}
